// counter/vue/src/App.vue
<template>
  <div>
    <h1>Counter {{count}}</h1>
    <button @click="count = 0">RESET</button>
    <StyledButton @click="count++">+1</StyledButton>
    <StyledButton @click="count--">-1</StyledButton>
  </div>
</template>

<script>
import StyledButton from './components/StyledButton.vue';

export default {
  name: 'App',
  components: {
    StyledButton,
  },
  data: () => ({
    count: 0,
  }),
};
</script>

// counter/reactjs/src/App.js
import { useState } from "react";
import StyledButton from "./components/StyledButton";

function App() {
  const [count, setCount] = useState(0);
  return (
    <div className="App">
      <h1>Counter {count}</h1>
      <button onClick={() => setCount(0)}>RESET</button>
      <StyledButton onClick={() => setCount(count + 1)}>+1</StyledButton>
      <StyledButton onClick={() => setCount(count - 1)}>-1</StyledButton>
    </div>
  );
}

export default App;
