// counter/reactjs/src/App.js
import { useState } from "react";
import StyledButton from "./components/StyledButton";

function App() {
  const [count, setCount] = useState(0);
  return (
    <div className="App">
      <h1>Counter {count}</h1>
      <button onClick={() => setCount(0)}>RESET</button>
      <StyledButton onClick={() => setCount(count + 1)}>+1</StyledButton>
      <StyledButton onClick={() => setCount(count - 1)}>-1</StyledButton>
    </div>
  );
}

export default App;

// counter/svelte/src/App.svelte
<script>
	import StyledButton from "./components/StyledButton.svelte";
	let count = 0;
</script>

<div>
	<h1>Counter {count}</h1>
	<button on:click={() => count = 0}>RESET</button>
	<StyledButton on:click={() => count++}>+1</StyledButton>
	<StyledButton on:click={() => count--}>-1</StyledButton>
</div>
